CREATE TABLE IF NOT EXISTS MEMBERS(
    MID         INT(8)  NOT NULL,
    ROLE        ENUM('STUDENT', 'PARLIAMENT', 'WARDEN', 'PROFESSOR', 'DEAN') NOT NULL,
    FIRSTNAME   VARCHAR(15) NOT NULL,
    LASTNAME    VARCHAR(25),
    BATCH       INT CHECK(BATCH > 1918 && BATCH < 2030) NOT NULL,
    BRANCH      ENUM('CSE', 'MNC', 'ECE', 'EEE', 'MEC', 'CHE', 'MET', 'MIN', 'CIV', 'CER', 'PHE', 'APD', 'NON') NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    EMAIL       VARCHAR(50) NOT NULL,
    PHONENUMBER CHAR(10) NOT NULL,
    PRIMARY KEY(MID, ROLE)
);
